# Generated by Django 5.0.1 on 2024-01-22 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='number',
            field=models.CharField(max_length=12),
        ),
    ]
