# Generated by Django 5.0.1 on 2024-01-22 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_alter_customer_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='razorpay_order_reciept',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
