# Generated by Django 5.0.1 on 2024-01-22 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_orders_razorpay_order_reciept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='products_info',
        ),
        migrations.AddField(
            model_name='orders',
            name='products_info',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
