# Generated by Django 5.0.1 on 2024-01-31 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_product_last_modified'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewInTheMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ManyToManyField(to='Store.product')),
            ],
        ),
    ]
