# Generated by Django 5.0.1 on 2024-05-01 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_newinthemenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
